Notes are created from completed tasks
cse110-sp24-group4/cse110-sp24-group4 pull request #113
Opened 2024-05-31 07:31 UTC by Kekoa-Pickett

Created "completedTasksToNotes()" that calls on the imported "createNoteFromTask(taskId, taskName)" and creates a note for each completed task. It then removes that task from the task list. Closes #95

2024-05-31 22:22 UTC, thedonutdan requested changes
This looks great! Lets get it integrated into our E2E testing though, make sure that when you mark a task as complete and press the add to notes button it creates new notes with the proper title.

2024-06-01 09:01 UTC, Kekoa-Pickett commented
Hey, could you please tell me how you're getting that issue. On my end, I am seeing the completed tasks name become the new notes title when we click add to notes.

2024-06-01 10:54 UTC, thedonutdan commented
> Hey, could you please tell me how you're getting that issue. On my end, I am seeing the completed tasks name become the new notes title when we click add to notes.

I'm not having any issues, my request was to incorporate checks into our E2E puppeteer testing to ensure we are testing that it works properly on the user's end. I believe the todo list tests are written by Vaibhav and the notes tests were mainly written by Joseph so if you need help get with them to get the tests written.

2024-06-04 22:55 UTC, Kekoa-Pickett commented
Alright, the E2E test has been added and makes sure the correct name and info is added when adding a completed task.

2024-06-05 04:04 UTC, thedonutdan commented on source/js/__testing__/puppeteer/task->note.test.js
this file needs to be renamed. git has trouble tracking file names with a chevron in them

2024-06-05 05:43 UTC, Kekoa-Pickett commented on source/js/__testing__/puppeteer/task->note.test.js
Sorry about that, just fixed it.

2024-06-05 05:45 UTC, thedonutdan approved these changes
Looks great!

2024-06-05 05:45 UTC, merged